stages:
  - build
  - test
  - deploy

before_script:
    - npm install
    - bower install

build-job:
    script:
        - grunt build
    stage: build
    allow_failure: true

test-job:
    script:
        - grunt test
    stage: test
    tags:
        - local

deploy-job:
    script:
        - grunt docs
        - cd ./docs/_site
        - zip -r artifact.zip ./*
        - rm -R /var/www/assul/www/ui.lussa.net/*
        - mv artifact.zip /var/www/assul/www/ui.lussa.net/
        - unzip /var/www/assul/www/ui.lussa.net/artifact.zip
    stage: deploy
    only:
        - master
    tags:
        - local
