stages:
  - build
  - test
  - deploy

before_script:
    - npm install
    - bower install

build-job:
    script:
        - grunt build
    stage: build

test-job:
    script:
        - grunt test
    stage: test
    tags:
        - local

deploy-development-job:
    script:
        - grunt docs
    stage: deploy
    except:
        - master
    tags:
        - local

deploy-production-job:
    script:
        - grunt docs
        - cd ./docs/_site
        - zip -r artifact.zip ./*
        - sudo rm -R /var/www/assul/www/ui.lussa.net/*
        - sudo mv artifact.zip /var/www/assul/www/ui.lussa.net/
        - cd /var/www/assul/www/ui.lussa.net/
        - sudo unzip artifact.zip
        - sudo rm artifact.zip
    stage: deploy
    only:
        - master
    tags:
        - local
