# Dependency
markdown: kramdown
highlighter: rouge

# Content
title: Tarsius-UI Docs
email: tarsius@lussa.net
description: > # Responsive, Mobile-First, Front-End Frameworks for Angular-Based App on Lussa Team, mainly on Tarsius-based projects. For Documentation reads the wiki or the Docs section.

# Server
baseurl: "/"
url: "http://ui.lussa.net"
source: "docs"
destination: "docs/_site"

# Custom Site Vars
current_version:  0.0.1
repo: https://github.com/lussatech/lussa-ui.git
